CREATE TABLE [dbo].[deleted](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Hostname] [varchar](5000) NULL,
	[Discovered] [datetime] NULL,
 CONSTRAINT [PK_deleted] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]